### ISSUE TITLE
DCIM Folder Missing & Can't Write Files

### ISSUE THREAD

**Issue by YofukashiNo** [Tiarait/HTTP-FS-file-server#10]
I'm using this application to wirelessly access my phone's storage from my Windows PC. Although Windows supports mapping to HTTP WebDAV servers, I've encountered an issue: the DCIM folder doesn't appear when I access the mapped drive. However, I can access it by manually entering the path in the directories.
Additionally, when attempting to copy files onto my phone, it creates dummy copies with no content, only the file name, rendering it unable to write files. Please refer to the attached video for context.

If it helps for reference, I've previously used an [older app that doesn't experience these issues but had to stop using it due to a lack of updates for newer Android versions and its outdated interface](https://play.google.com/store/apps/details?id=com.theolivetree.webdavserver&hl=en&gl=US).

https://github.com/Tiarait/HTTP-FS-file-server/assets/73281112/dc391280-dc26-422f-97bd-a659738f38e8

**Comment by Tiarait** [comment]
Thanks for the video and detailed description. I finally managed to fix this error in [WebDAV FS](https://github.com/Tiarait/WebDav-FS), but the update for HTTP FS is not ready yet (I'm planning a big update with all the edits and redesign).

**Comment by YofukashiNo** [comment]
> Thanks for the video and detailed description. I finally managed to fix this error in [WebDAV FS](https://github.com/Tiarait/WebDav-FS) in next version (1.0.16), but the update for HTTP FS is not ready yet (I'm planning a big update with all the edits and redesign).

I checked the update of WebDav FS and it seems I can create files. But the other issue of not DCIM folder not showing up persists.

Also, it doesn't ask for the permissions required to make files on the phone itself (All File Access Special Permissions) nor does it prompt the user to add the add for unrestricted battery usage due to which it stops working as soon as the screen is off or using another app.

**Comment by YofukashiNo** [comment]
Updated to v1.1.2, it fixed all of the issues other than DCIM folder.
The folder shows up on the web interface but not in the mapped drive on Windows.
My phone is Samsung Galaxy M34 running One UI 6.0
![image](https://github.com/Tiarait/HTTP-FS-file-server/assets/73281112/4dc0c9ec-b9d7-4d53-be00-cc9f6747654f)
![image](https://github.com/Tiarait/HTTP-FS-file-server/assets/73281112/92b494e2-1517-41ce-825a-aeb3664911b2)
![image](https://github.com/Tiarait/HTTP-FS-file-server/assets/73281112/566c78be-5a95-48ab-a473-cbef56257330)

**Comment by YofukashiNo** [comment]
v1.1.4 Everything seems to be working fine, thank you a lot.

By the way, when I click to disable battery restriction in settings, it opens general battery settings instead of battery settings for app.

**Comment by Tiarait** [comment]
Glad to hear that. 

I probably won't do anything about this for now. Android does not have any standard functions for the battery, so I use it from [WaseemSabir](https://github.com/WaseemSabir/BatteryPermissionHelper)
