### ISSUE TITLE
bug : A problem repeatedly occurred on "http://192.168.1.*:8080/files"

### ISSUE THREAD

**Issue by UnVzaGFu** [Tiarait/HTTP-FS-file-server#19]
This is such a beautiful app, just a shame that I can't access the web page on my iPhone 6s Plus, the page keeps refreshing and then the page stops displaying and the browser prompts an error:A problem repeatedly occurred on "http://192.168.1.168:8080/files" .
Tested both safari and chrome browsers and both have this problem.
Lastly, I wish Ukraine a quick victory, go Ukraine!

**Comment by Tiarait** [comment]
Thanks for your feedback.
I fixed most of the old problems. The redesign also includes optimizations for Safari.

Now I'm waiting for confirmation from Google to publish 1.1.2 for the free version, as soon as it is released I will need to check this problem again.
