### ISSUE TITLE
V1.0.23 crash with ssl

### ISSUE THREAD

**Issue by Tiarait** [Tiarait/HTTP-FS-file-server#2]
**v1.0.23**
Device: **Pocco x3** Android: **10**

> [!IMPORTANT]
> Application crashes when stopping server ***if SSL is enabled***

Start the server -> make some requests -> Stop the server  -> Crash

```
E/ActivityManager: ANR in com.android.se
    PID: 9522
    Reason: executing service com.android.se/.SecureElementService
    Load: 0.0 / 0.0 / 0.0
    CPU usage from 20285ms to 0ms ago (2023-12-20 18:28:48.580 to 2023-12-20 18:29:08.864):
```

```
W/ActivityTaskManager:   Force finishing activity tiar.ua.slf/.ui.MainActivity
```

**Comment by Tiarait** [comment]
https://github.com/Tiarait/HTTP-FS-file-server/assets/25516389/7f851787-67ef-4476-bcf4-2f2e7c952b3b

**Comment by snkllc** [comment]
I think you might want to reproduce the app and try the cloned app on a platform like Azures test site or on a similar type of demo platform

**Comment by Tiarait** [comment]
So I had to go inside the library and rewrite NettyApplicationEngine. The error has disappeared but I don’t know if it will cause new problems. I'll test it again but I don't see any other solution
