### ISSUE TITLE
Not sure where to ask this question

### ISSUE THREAD

**Issue by KParthSingh** [Tiarait/HTTP-FS-file-server#20]
I want to know what is the difference between the HTTP FS and WebDAV FS?

btw i love your application http fs thanks for your hardwork.

**Comment by Tiarait** [comment]
It's better to write by email tiar.develop@gmail.com

In fact, there is not much difference yet. Webdav Fs uses the same webdav server code as Http Fs (I try to make it look the same). One difference is that Webdav Fs has an FTP server. And further I plan to improve only these two aspects

If you need pure Webdav or FTP then it is better to use Webdav Fs, if you need Http server (with better web client side) then it is Http Fs

**Comment by KParthSingh** [comment]
Alright thanks for the response.
