### ISSUE TITLE
Where are the source files? I want to add Dutch language to the software.

### ISSUE THREAD

**Issue by GerbenAaltink** [Tiarait/HTTP-FS-file-server#45]
Hi, is there any way i can contribute? I want  to add Dutch language to the application. You can contact me @ gerbenaaltink@gmail.com if me contributing is appreciated. If you just send me a file with all labels it's also OK. I will translate that then.

**Comment by Tiarait** [comment]
I'll try to add it in the next updates, I also posted the [sources of the strings](https://github.com/Tiarait/HTTP-FS-file-server/blob/main/res/values/strings.xml)

And of course I wrote to you. Thanks for your help
